# Load Balancer
lb:
  image: jwilder/nginx-proxy
  environment:
    - security-opt=label:type:docker_t
  ports:
    - "80:80"
  volumes:
    - "/var/run/docker.sock:/tmp/docker.sock"

# httpd
web:
    image: nginx
    environment:
        - VIRTUAL_HOST=nuts.jp
    ports:
        - "40000"

# WordPress
wp:
    image: nuts/wp
    links:
        - db:mysql
    environment:
        - VIRTUAL_HOST=wp.nuts.jp
    ports:
        - "40100"
db:
    image: mariadb
    volumes_from:
        - db-data
    environment:
        MYSQL_ROOT_PASSWORD: root
db-data:
    image: busybox
    volumes:
        - /var/lib/mysql

# OwnCloud
cloud:
    image: owncloud
    environment:
        - VIRTUAL_HOST=cloud.nuts.jp
    ports:
        - "40110"

# shipyard
rethinkdb:
    image: rethinkdb
    ports:
        - "8080"
        - "28015"
        - "29015"
proxy:
    image: ehazlett/docker-proxy:latest
    command: -i
    volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
        - "2375"
swarm:
    image: swarm:latest
    command: m --host tcp://0.0.0.0:2375 proxy:2375
    links:
        - "proxy:proxy"
    ports:
        - "2375"
media:
    build: src/shipyard/Dockerfile
    dockerfile: src/shipyard/Dockerfile.build
    entrypoint: /bin/bash
    command: -c "make media && sleep infinity"
    working_dir: /go/src/github.com/shipyard/shipyard
    volumes:
        - "/go/src/github.com/shipyard/shipyard/controller/static"
controller:
    build: src/shipyard/Dockerfile.
    dockerfile: src/shipyard/Dockerfile.build
    entrypoint: /bin/bash
    command: -c "make build && cd controller && ./controller -D server --rethinkdb-addr rethinkdb:28015 -d tcp://swarm:2375"
    links:
        - rethinkdb
        - swarm
    volumes_from:
        - media
    environment:
        - VIRTUAL_HOST=shipyard.nuts.jp
    ports:
        - "8080:8080"
