#!/bin/bash

project_name=toybox
name=$(basename $0)
version=0.1.0

function _version() { 
    echo $version 
}

function _help() { 
    usage 
}

function usage() {
  cat <<-EOF
Usage: ${name} <command>

command:
    init        Create docker-compose.yml and data directory
    start       Start ${name} containers
    stop        Stop ${name} containers
    state       Show ${name} containers status
    clear       Stop and Remove all of ${name} containers
    backup      Backup DB data
    source      get source code of containers

    version     Show the version of ${name}
    help        Show this message
EOF
}

self_path=$(cd $(dirname $0);pwd)
out=${self_path}/bin/docker-compose.yml
src=${self_path}/src
url=${name}.nuts.jp

#db_name=owncloud
#db_user=owncloud
#db_user_pass=owncloud

function _source() {
    mkdir -p $src
    if [ -e $src/Dockerfile ]; then
        rm $src/Dockerfile
    fi
    cat <<-EOF > $src/Dockerfile
FROM node:0.12.2
RUN npm install -g reichat
EXPOSE 10133
CMD reichat
EOF
}

function _build() {
    _source
    docker build -t nutsp/reichat $src
}

function _init() {
    mkdir -p ${self_path}/bin
    if [ -e $out ]; then
        rm $out
    fi

    _source
    _build

    cat <<-EOF > $out
${name}:
    #build: $src
    image: nutsp/reichat
    volumes:
        - /usr/local/lib/node_modules/reichat
    environment:
        - VIRTUAL_HOST=${url}
    ports:
        - "10133"
EOF
}

function _start() {
    _init
    cd ${self_path}/bin
    docker-compose -p ${project_name} up -d
    echo '---------------------------------'
    echo 'URL: http://'${url}
    echo '---------------------------------'
}

function _stop() {
    cd ${self_path}/bin
    docker-compose -p ${project_name} stop
}

function _rm() {
    cd ${self_path}/bin
    docker-compose -p ${project_name} rm
}

function _state() {
    cd ${self_path}/bin
    docker-compose -p ${project_name} ps
}

function _clear() {
    _backup
    _stop
    cd ${self_path}/bin
    docker-compose -p ${project_name} rm
}

#function _backup() {
#    prefix=$(date '+%Y%m%d_%H%M%S')
#    history_file=${self_path}/backup/history.txt
#    mkdir -p ${self_path}/backup
#    if [ ! -e $history_file ]; then
#        echo "" >> ${history_file}    
#    fi
#    sed -i -e "1s/^/${prefix}\n/" ${history_file}
#    docker run --rm --volumes-from $(docker ps -a | grep ${project_name}_${name}_1 | awk '{print $1}') -v ${self_path}/backup:/backup busybox tar cvzf /backup/${prefix}.tar.gz /usr/local/lib/node_modules/reichat
#}
#
#function _restore() {
#    prefix=$(cat ${self_path}/backup/history.txt | peco)
#    docker run --rm --volumes-from $(docker ps -a | grep ${project_name}_${name}_1 | awk '{print $1}') -v ${self_path}/backup:/backup busybox tar xvzf /backup/${prefix}.tar.gz
#    _stop
#    _start
#}

# check arguments
if [ $# -ne 1 ]; then
  usage
  exit 1
fi

function _is_executable() {
    local command="$1"
    type "$command" > /dev/null 2>&1
}

sub=$1

if _is_executable "_${sub}" ; then
    _${sub}
else
    echo "$name: no such command \"${sub}\""
    usage
    exit 1
fi

exit 0


