#!/bin/bash

name=`basename $0`
version=0.1.0

db_name=lychee
db_user=lychee
db_user_pass=lychee

function _version() { 
    echo $version 
}

function _help() { 
    usage 
}

function usage() {
  cat <<-EOF
Usage: ${name} <command>

command:
    init        Create docker-compose.yml and data directory
    start       Start ${name} containers
    stop        Stop ${name} containers
    state       Show ${name} containers status
    clear       Stop and Remove all of ${name} containers
    backup      Backup DB data

    version     Show the version of ${name}
    help        Show this message
EOF
}

function _init() {
    
    out=docker-compose.yml
    domainname=nuts.jp
    url_lychee=lychee.${domainname}
    
    if [ -e $out ]; then
        rm $out
    fi
    
    cat <<-EOF > $out

lychee:
    image: nutsp/lychee
    environment:
        - VIRTUAL_HOST=${url_lychee}
    links:
        - lychee-db:lychee-mysql
    volumes_from:
        - lychee-data
    ports:
        - "80"
lychee-db:
    image: mariadb
    volumes_from:
        - lychee-data
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: ${db_name}
        MYSQL_USER: ${db_user}
        MYSQL_PASSWORD: ${db_user_pass}
lychee-data:
    image: busybox
    volumes:
        - /var/lib/mysql
        - /var/www/lychee/data
        - /var/www/lychee/uploads/big
        - /var/www/lychee/uploads/medium
        - /var/www/lychee/uploads/thumb
        - /var/www/lychee/uploads/import
EOF
}

function build() {
    docker
}

#function _init() {
#    
#    #mkdir -p $(dirname $0)/data/uploads/big
#    #mkdir -p $(dirname $0)/data/uploads/medium
#    #mkdir -p $(dirname $0)/data/uploads/thumb
#    #mkdir -p $(dirname $0)/data/uploads/import
#    #chmod -R 777 $(dirname $0)/data
#    
#    out=docker-compose.yml
#    domainname=nuts.jp
#    url_lychee=lychee.${domainname}
#    
#    if [ -e $out ]; then
#        rm $out
#    fi
#    
#    echo 'lychee:' >> ${out}
#    echo '    image: nutsp/lychee' >> ${out}
#    echo '    environment:' >> ${out}
#    echo '        - VIRTUAL_HOST='${url_lychee} >> ${out}
#    echo '    links:' >> ${out}
#    echo '        - lychee-db:lychee-mysql' >> ${out}
#    #echo '    volumes:' >> ${out}
#    #echo '        - '$(pwd)'/data/uploads/:/uploads/' >> ${out}
#    echo '    volumes_from:' >> ${out}
#    echo '        - lychee-data' >> ${out}
#    echo '    ports:' >> ${out}
#    echo '        - "80"' >> ${out}
#    echo 'lychee-db:' >> ${out}
#    echo '    image: mariadb' >> ${out}
#    echo '    volumes_from:' >> ${out}
#    echo '        - lychee-data' >> ${out}
#    echo '    environment:' >> ${out}
#    echo '        MYSQL_ROOT_PASSWORD: root' >> ${out}
#    echo '        MYSQL_DATABASE: '${db_name} >> ${out}
#    echo '        MYSQL_USER: '${db_user} >> ${out}
#    echo '        MYSQL_PASSWORD: '${db_user_pass} >> ${out}
#    echo 'lychee-data:' >> ${out}
#    echo '    image: busybox' >> ${out}
#    echo '    volumes:' >> ${out}
#    echo '        - /var/lib/mysql' >> ${out}
#    echo '        - /var/www/lychee/data' >> ${out}
#    echo '        - /var/www/lychee/uploads/big' >> ${out}
#    echo '        - /var/www/lychee/uploads/medium' >> ${out}
#    echo '        - /var/www/lychee/uploads/thumb' >> ${out}
#    echo '        - /var/www/lychee/uploads/import' >> ${out}
#    echo '' >> ${out}
#    echo 'init done'
#}

function _start() {
    docker-compose up -d
    echo -n 'Database Host: '
    docker inspect -f '{{ .NetworkSettings.IPAddress }}' \
        $(docker ps | grep lychee_lychee-db_1 | awk '{print $1}')
    echo 'Database Username: '${db_user}
    echo 'Database Password: '${db_user_pass}
}

#function _start() {
#    docker-compose start
#}

function _stop() {
    docker-compose stop
}

#function _rm() {
#    _backup
#    docker-compose rm
#}

function _state() {
    docker-compose ps
}

function _clear() {
    _backup
    _stop
    docker-compose rm
}

function _backup() {
    prefix=$(date '+%Y%m%d_%H%M%S')
    history_file=$(dirname $0)/backup/history.txt
    mkdir -p $(dirname $0)/backup
    if [ ! -e $history_file ]; then
        echo "" >> ${history_file}    
    fi
    sed -i -e "1s/^/${prefix}\n/" ${history_file}
    docker run --rm --volumes-from $(docker ps -a | grep lychee_lychee-data_1 | awk '{print $1}') -v $(pwd)/backup:/backup busybox tar cvzf /backup/${prefix}_db.tar.gz /var/lib/mysql
    docker run --rm --volumes-from $(docker ps -a | grep lychee_lychee-data_1 | awk '{print $1}') -v $(pwd)/backup:/backup busybox tar cvzf /backup/${prefix}_images.tar.gz /var/www/lychee/uploads
    docker run --rm --volumes-from $(docker ps -a | grep lychee_lychee-data_1 | awk '{print $1}') -v $(pwd)/backup:/backup busybox tar cvzf /backup/${prefix}.tar.gz /var/www/lychee/data
}

function _restore() {
    #prefix=$(ls -la $(dirname $0)/backup/ | peco | awk '{print $10}' | sed "s/_[a-z]*\.tar\.gz$//")
    prefix=$(cat $(dirname $0)/backup/history.txt | peco)
    docker run --rm --volumes-from $(docker ps -a | grep lychee_lychee-data_1 | awk '{print $1}') -v $(pwd)/backup:/backup busybox tar xvzf /backup/${prefix}_db.tar.gz
    docker run --rm --volumes-from $(docker ps -a | grep lychee_lychee-data_1 | awk '{print $1}') -v $(pwd)/backup:/backup busybox tar xvzf /backup/${prefix}_images.tar.gz
    docker run --rm --volumes-from $(docker ps -a | grep lychee_lychee-data_1 | awk '{print $1}') -v $(pwd)/backup:/backup busybox tar xvzf /backup/${prefix}.tar.gz
    _stop
    _start
    #docker exec -t $(docker ps -a | grep lychee_lychee_1 | awk '{print $1}') sh /entrypoint.sh
}

# check arguments
if [ $# -ne 1 ]; then
  usage
  exit 1
fi

function _is_executable() {
    local command="$1"
    type "$command" > /dev/null 2>&1
}

sub=$1

if _is_executable "_${sub}" ; then
    _${sub}
else
    echo "$name: no such command \"${sub}\""
    usage
    exit 1
fi

exit 0


