#!/bin/bash

project_name=toybox
name=$(basename $0)
version=0.1.0

function _version() { 
    echo $version 
}

function _help() { 
    usage 
}

function usage() {
  cat <<-EOF
Usage: ${name} <command>

command:
    init        Create docker-compose.yml and data directory
    start       Start ${name} containers
    stop        Stop ${name} containers
    state       Show ${name} containers status
    clear       Stop and Remove all of ${name} containers
    backup      Backup DB data

    version     Show the version of ${name}
    help        Show this message
EOF
}

self_path=$(cd $(dirname $0);pwd)
out=${self_path}/bin/docker-compose.yml
src=${self_path}/../../src/${name}
url=${name}.nuts.jp

db_name=lychee
db_user=lychee
db_user_pass=lychee

function _source() {
    if [ ! -e $src ]; then
        git clone https://github.com/docker-library/wordpress.git $src
    fi
}

function _build() {
    docker build -t nutsp/lychee ${self_path}/src
}

function _init() {
    
    mkdir -p ${self_path}/bin
    if [ -e $out ]; then
        rm $out
    fi

    _build
    
    cat <<-EOF > $out
${name}:
    image: nutsp/lychee
    environment:
        - VIRTUAL_HOST=${url}
    links:
        - lychee-db:lychee-mysql
    volumes_from:
        - lychee-data
    ports:
        - "80"
${name}-db:
    image: mariadb
    volumes_from:
        - lychee-data
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: ${db_name}
        MYSQL_USER: ${db_user}
        MYSQL_PASSWORD: ${db_user_pass}
${name}-data:
    image: busybox
    volumes:
        - /var/lib/mysql
        - /var/www/lychee/data
        - /var/www/lychee/uploads/big
        - /var/www/lychee/uploads/medium
        - /var/www/lychee/uploads/thumb
        - /var/www/lychee/uploads/import
EOF
}

function _start() {
    _init
    cd ${self_path}/bin
    docker-compose -p ${project_name} up -d
    echo '---------------------------------'
    echo 'URL: http://'${url}
    echo '---------------------------------'
    echo -n 'Database Host: '
    docker inspect -f '{{ .NetworkSettings.IPAddress }}' \
        $(docker ps | grep ${project_name}_${name}-db_1 | awk '{print $1}')
    echo 'Database Username: '${db_user}
    echo 'Database Password: '${db_user_pass}
    echo 'New Username: username as you like'
    echo 'New Password: password as you like'
}

function _stop() {
    cd ${self_path}/bin
    docker-compose -p ${project_name} stop
}

function _rm() {
    cd ${self_path}/bin
    docker-compose -p ${project_name} rm
}

function _state() {
    cd ${self_path}/bin
    docker-compose -p ${project_name} ps
}

function _clear() {
    _backup
    _stop
    echo '---------------------------------'
    cd ${self_path}/bin
    docker-compose -p ${project_name} rm
}

function _backup() {
    prefix=$(date '+%Y%m%d_%H%M%S')
    history_file=${self_path}/backup/history.txt
    mkdir -p ${self_path}/backup
    if [ ! -e $history_file ]; then
        echo "" >> ${history_file}    
    fi
    sed -i -e "1s/^/${prefix}\n/" ${history_file}
    docker run --rm --volumes-from $(docker ps -a | grep ${project_name}_${name}-data_1 | awk '{print $1}') -v ${self_path}/backup:/backup busybox tar cvzf /backup/${prefix}_db.tar.gz /var/lib/mysql
    docker run --rm --volumes-from $(docker ps -a | grep ${project_name}_${name}-data_1 | awk '{print $1}') -v ${self_path}/backup:/backup busybox tar cvzf /backup/${prefix}_images.tar.gz /var/www/lychee/uploads
    docker run --rm --volumes-from $(docker ps -a | grep ${project_name}_${name}-data_1 | awk '{print $1}') -v ${self_path}/backup:/backup busybox tar cvzf /backup/${prefix}.tar.gz /var/www/lychee/data
}

function _restore() {
    #prefix=$(ls -la $(dirname $0)/backup/ | peco | awk '{print $10}' | sed "s/_[a-z]*\.tar\.gz$//")
    prefix=$(cat $(dirname $0)/backup/history.txt | peco)
    docker run --rm --volumes-from $(docker ps -a | grep ${project_name}_${name}-data_1 | awk '{print $1}') -v ${self_path}/backup:/backup busybox tar xvzf /backup/${prefix}_db.tar.gz
    docker run --rm --volumes-from $(docker ps -a | grep ${project_name}_${name}-data_1 | awk '{print $1}') -v ${self_path}/backup:/backup busybox tar xvzf /backup/${prefix}_images.tar.gz
    docker run --rm --volumes-from $(docker ps -a | grep ${project_name}_${name}-data_1 | awk '{print $1}') -v ${self_path}/backup:/backup busybox tar xvzf /backup/${prefix}.tar.gz
    _stop
    _start
    #docker exec -t $(docker ps -a | grep lychee_lychee_1 | awk '{print $1}') sh /entrypoint.sh
}

# check arguments
if [ $# -ne 1 ]; then
  usage
  exit 1
fi

function _is_executable() {
    local command="$1"
    type "$command" > /dev/null 2>&1
}

sub=$1

if _is_executable "_${sub}" ; then
    _${sub}
else
    echo "$name: no such command \"${sub}\""
    usage
    exit 1
fi

exit 0


